set -eu
mkdir -p .ai/sprints
if [ -f .ai/current_sprint_id.txt ]; then
  sid=$(cat .ai/current_sprint_id.txt)
else
  sid=001
fi
file=.ai/sprints/SPRINT-${sid}.md
if [ ! -f "$file" ]; then
  printf '# Sprint %s\n\nGenerated by megaplan. See run logs for full model output.\n' "$sid" > "$file"
fi
printf 'persisted-%s' "$sid"